import * as Crypto from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';
import { readTrustAnchorReadinessPassport } from './trustAnchorPassport';
import { deriveTrustCeremonyPolicyDigest, trustCeremonyPolicy, TRUST_CEREMONY_RELEASE } from './trustCeremonyContract';
import { deriveProviderTrustRegistryPolicyDigest, providerTrustRegistryPolicy, PROVIDER_TRUST_REGISTRY_RELEASE } from './providerTrustRegistry';
import { deriveServerVerificationProfilePolicyDigest, serverVerificationProfilePolicy, SERVER_VERIFICATION_PROFILE_RELEASE } from './serverVerificationProfile';
import { deriveExternalTrustReadinessPolicyDigest, externalTrustReadinessPolicy, EXTERNAL_TRUST_READINESS_RELEASE } from './externalTrustReadinessGate';
import { deriveStagingHsmP256BindingDigest, stagingHsmP256Binding, stagingHsmP256BindingPolicy } from './stagingHsmP256Binding';

const KEY='orchidpay.external.trust.readiness.passport.v2';
const VERSION=2 as const;
const secureStoreOptions:SecureStore.SecureStoreOptions={keychainAccessible:SecureStore.WHEN_PASSCODE_SET_THIS_DEVICE_ONLY};

export type ExternalTrustReadinessPassport={
  v:2;issuedAt:number;status:'STAGING_HSM_P256_ATTESTED_PROVIDER_REVIEW_PRODUCTION_BLOCKED';
  parentTrustProof:string;parentRemoteProof:string;parentAuthorizationProof:string;parentReplayProof:string;parentBackendProof:string;
  boundaryLineage:string;contractLineage:string;suitePassed:344;suiteTotal:344;scope:'STAGING_HSM_P256_SHADOW_READINESS_ONLY';
  trustCeremonyRelease:typeof TRUST_CEREMONY_RELEASE;providerRegistryRelease:typeof PROVIDER_TRUST_REGISTRY_RELEASE;serverVerificationRelease:typeof SERVER_VERIFICATION_PROFILE_RELEASE;externalTrustGateRelease:typeof EXTERNAL_TRUST_READINESS_RELEASE;
  stagingHsmBindingDigest:string;stagingHsmEvidenceSha256:typeof stagingHsmP256Binding.r13_8dR2BundleSha256;stagingHsmP256Verified:true;stagingHsmAttestationVerified:true;manufacturerRootCurrentTimeValid:false;
  productionKms:false;productionKeyMaterial:false;serverVerifier:false;providerTrustRoots:false;serverReplayLedger:false;trustedServerClock:false;productionRelease:false;networkExecution:false;livePaymentExecution:false;settlement:false;
  ceremonyPolicyDigest:string;providerPolicyDigest:string;serverVerificationPolicyDigest:string;externalTrustPolicyDigest:string;proof:string;
};
type Core=Omit<ExternalTrustReadinessPassport,'proof'>;
async function sha(value:string){return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,value);}
function upper16(hex:string){return hex.slice(0,16).toUpperCase();}
function canonical(value:Core){return[value.v,value.issuedAt,value.status,value.parentTrustProof,value.parentRemoteProof,value.parentAuthorizationProof,value.parentReplayProof,value.parentBackendProof,value.boundaryLineage,value.contractLineage,value.suitePassed,value.suiteTotal,value.scope,value.trustCeremonyRelease,value.providerRegistryRelease,value.serverVerificationRelease,value.externalTrustGateRelease,value.stagingHsmBindingDigest,value.stagingHsmEvidenceSha256,value.stagingHsmP256Verified?1:0,value.stagingHsmAttestationVerified?1:0,value.manufacturerRootCurrentTimeValid?1:0,value.productionKms?1:0,value.productionKeyMaterial?1:0,value.serverVerifier?1:0,value.providerTrustRoots?1:0,value.serverReplayLedger?1:0,value.trustedServerClock?1:0,value.productionRelease?1:0,value.networkExecution?1:0,value.livePaymentExecution?1:0,value.settlement?1:0,value.ceremonyPolicyDigest,value.providerPolicyDigest,value.serverVerificationPolicyDigest,value.externalTrustPolicyDigest].join('|');}

export async function issueExternalTrustReadinessPassport(suitePassed:number,suiteTotal:number){try{
  if(suitePassed!==344||suiteTotal!==344)return{ok:false as const,reason:'EXTERNAL_TRUST_SUITE_NOT_344_344'};
  if(!(await SecureStore.isAvailableAsync()))return{ok:false as const,reason:'SECURESTORE_UNAVAILABLE'};
  const parent=await readTrustAnchorReadinessPassport(); if(!parent.valid||!parent.passport)return{ok:false as const,reason:'VALID_TRUST_ANCHOR_PASSPORT_REQUIRED'};
  if(parent.passport.productionKeySet||parent.passport.serverSignatureVerifier||parent.passport.deviceAttestationVerifier||parent.passport.serverReplayLedger||parent.passport.trustedServerClock||parent.passport.productionRelease||parent.passport.networkExecution||parent.passport.livePaymentExecution||parent.passport.settlement)return{ok:false as const,reason:'PARENT_TRUST_FUSE_OPEN'};
  if(!stagingHsmP256BindingPolicy.hsmKeyProvisioned||!stagingHsmP256BindingPolicy.attestationVerified||!stagingHsmP256BindingPolicy.resourceBindingVerified||!stagingHsmP256BindingPolicy.publicKeyBindingVerified||!stagingHsmP256BindingPolicy.privateKeyNonExtractableVerified||!stagingHsmP256BindingPolicy.privateKeyLocalGenerationVerified||stagingHsmP256BindingPolicy.manufacturerRootCurrentTimeValid||stagingHsmP256BindingPolicy.productionEligible)return{ok:false as const,reason:'STAGING_HSM_BINDING_POLICY'};
  if(!trustCeremonyPolicy.stagingHsmP256Provisioned||!trustCeremonyPolicy.stagingHsmAttestationVerified||trustCeremonyPolicy.productionKmsProvisioned||trustCeremonyPolicy.productionKeyMaterialImported||trustCeremonyPolicy.remoteCeremonyServiceProvisioned||trustCeremonyPolicy.networkExecutionEnabled||trustCeremonyPolicy.productionCeremonyClaim)return{ok:false as const,reason:'CEREMONY_FUSE_OPEN'};
  if(providerTrustRegistryPolicy.appleProviderRootsProvisioned||providerTrustRegistryPolicy.androidProviderRootsProvisioned||providerTrustRegistryPolicy.providerVerifiersProvisioned||providerTrustRegistryPolicy.networkExecutionEnabled||providerTrustRegistryPolicy.strongProviderTrustClaim)return{ok:false as const,reason:'PROVIDER_FUSE_OPEN'};
  if(!serverVerificationProfilePolicy.stagingHsmP256Provisioned||!serverVerificationProfilePolicy.stagingHsmAttestationVerified||serverVerificationProfilePolicy.productionVerifierProvisioned||serverVerificationProfilePolicy.productionKeySetProvisioned||serverVerificationProfilePolicy.serverReplayLedgerProvisioned||serverVerificationProfilePolicy.trustedServerClockProvisioned||serverVerificationProfilePolicy.networkExecutionEnabled||serverVerificationProfilePolicy.livePaymentExecutionEnabled||serverVerificationProfilePolicy.strongServerVerificationClaim)return{ok:false as const,reason:'SERVER_VERIFICATION_FUSE_OPEN'};
  if(!externalTrustReadinessPolicy.stagingHsmP256Provisioned||!externalTrustReadinessPolicy.stagingHsmAttestationVerified||externalTrustReadinessPolicy.manufacturerRootCurrentTimeValid||!externalTrustReadinessPolicy.providerReviewStagingExceptionAccepted||!externalTrustReadinessPolicy.productionProviderRootGateOpen||externalTrustReadinessPolicy.ceremonyEvidenceProvisioned||externalTrustReadinessPolicy.productionKmsProvisioned||externalTrustReadinessPolicy.serverVerifierProvisioned||externalTrustReadinessPolicy.providerTrustRootsProvisioned||externalTrustReadinessPolicy.serverReplayLedgerProvisioned||externalTrustReadinessPolicy.trustedServerClockProvisioned||externalTrustReadinessPolicy.networkExecutionEnabled||externalTrustReadinessPolicy.livePaymentExecutionEnabled||externalTrustReadinessPolicy.settlementEnabled||externalTrustReadinessPolicy.productionReleaseClaim)return{ok:false as const,reason:'EXTERNAL_TRUST_GATE_FUSE_OPEN'};
  const[ceremonyPolicyDigest,providerPolicyDigest,serverVerificationPolicyDigest,externalTrustPolicyDigest,stagingHsmBindingDigest]=await Promise.all([deriveTrustCeremonyPolicyDigest(),deriveProviderTrustRegistryPolicyDigest(),deriveServerVerificationProfilePolicyDigest(),deriveExternalTrustReadinessPolicyDigest(),deriveStagingHsmP256BindingDigest()]);
  const core:Core={v:VERSION,issuedAt:Date.now(),status:'STAGING_HSM_P256_ATTESTED_PROVIDER_REVIEW_PRODUCTION_BLOCKED',parentTrustProof:parent.passport.proof,parentRemoteProof:parent.passport.parentRemoteProof,parentAuthorizationProof:parent.passport.parentAuthorizationProof,parentReplayProof:parent.passport.parentReplayProof,parentBackendProof:parent.passport.parentBackendProof,boundaryLineage:parent.passport.boundaryLineage,contractLineage:parent.passport.contractLineage,suitePassed:344,suiteTotal:344,scope:'STAGING_HSM_P256_SHADOW_READINESS_ONLY',trustCeremonyRelease:TRUST_CEREMONY_RELEASE,providerRegistryRelease:PROVIDER_TRUST_REGISTRY_RELEASE,serverVerificationRelease:SERVER_VERIFICATION_PROFILE_RELEASE,externalTrustGateRelease:EXTERNAL_TRUST_READINESS_RELEASE,stagingHsmBindingDigest,stagingHsmEvidenceSha256:stagingHsmP256Binding.r13_8dR2BundleSha256,stagingHsmP256Verified:true,stagingHsmAttestationVerified:true,manufacturerRootCurrentTimeValid:false,productionKms:false,productionKeyMaterial:false,serverVerifier:false,providerTrustRoots:false,serverReplayLedger:false,trustedServerClock:false,productionRelease:false,networkExecution:false,livePaymentExecution:false,settlement:false,ceremonyPolicyDigest,providerPolicyDigest,serverVerificationPolicyDigest,externalTrustPolicyDigest};
  const out:ExternalTrustReadinessPassport={...core,proof:`ETP-${upper16(await sha(canonical(core)))}`}; await SecureStore.setItemAsync(KEY,JSON.stringify(out),secureStoreOptions); return{ok:true as const,passport:out};
}catch{return{ok:false as const,reason:'EXTERNAL_TRUST_PASSPORT_WRITE_FAILED'};}}

export async function readExternalTrustReadinessPassport():Promise<{valid:boolean;passport:ExternalTrustReadinessPassport|null;error:string}>{try{
  if(!(await SecureStore.isAvailableAsync()))return{valid:false,passport:null,error:'SECURESTORE_UNAVAILABLE'};const raw=await SecureStore.getItemAsync(KEY,secureStoreOptions);if(!raw)return{valid:true,passport:null,error:''};const p=JSON.parse(raw) as ExternalTrustReadinessPassport;
  if(p.v!==VERSION||p.status!=='STAGING_HSM_P256_ATTESTED_PROVIDER_REVIEW_PRODUCTION_BLOCKED'||p.suitePassed!==344||p.suiteTotal!==344||p.scope!=='STAGING_HSM_P256_SHADOW_READINESS_ONLY'||p.trustCeremonyRelease!==TRUST_CEREMONY_RELEASE||p.providerRegistryRelease!==PROVIDER_TRUST_REGISTRY_RELEASE||p.serverVerificationRelease!==SERVER_VERIFICATION_PROFILE_RELEASE||p.externalTrustGateRelease!==EXTERNAL_TRUST_READINESS_RELEASE||p.stagingHsmEvidenceSha256!==stagingHsmP256Binding.r13_8dR2BundleSha256||p.stagingHsmP256Verified!==true||p.stagingHsmAttestationVerified!==true||p.manufacturerRootCurrentTimeValid!==false||p.productionKms!==false||p.productionKeyMaterial!==false||p.serverVerifier!==false||p.providerTrustRoots!==false||p.serverReplayLedger!==false||p.trustedServerClock!==false||p.productionRelease!==false||p.networkExecution!==false||p.livePaymentExecution!==false||p.settlement!==false||!Number.isSafeInteger(p.issuedAt)||p.issuedAt<=0||!/^TAP-[A-F0-9]{16}$/.test(p.parentTrustProof)||!/^RAP-[A-F0-9]{16}$/.test(p.parentRemoteProof)||!/^IAP-[A-F0-9]{16}$/.test(p.parentAuthorizationProof)||!/^IRP-[A-F0-9]{16}$/.test(p.parentReplayProof)||!/^BC-[A-F0-9]{16}$/.test(p.parentBackendProof)||!/^IBL-[A-F0-9]{16}$/.test(p.boundaryLineage)||!/^BCL-[A-F0-9]{16}$/.test(p.contractLineage)||!/^HSMB-[A-F0-9]{16}$/.test(p.stagingHsmBindingDigest)||!/^TCPOL-[A-F0-9]{16}$/.test(p.ceremonyPolicyDigest)||!/^PTRPOL-[A-F0-9]{16}$/.test(p.providerPolicyDigest)||!/^SVPPOL-[A-F0-9]{16}$/.test(p.serverVerificationPolicyDigest)||!/^ETPOL-[A-F0-9]{16}$/.test(p.externalTrustPolicyDigest)||!/^ETP-[A-F0-9]{16}$/.test(p.proof))return{valid:false,passport:null,error:'STRUCTURE'};
  const[ceremonyPolicyDigest,providerPolicyDigest,serverVerificationPolicyDigest,externalTrustPolicyDigest,stagingHsmBindingDigest]=await Promise.all([deriveTrustCeremonyPolicyDigest(),deriveProviderTrustRegistryPolicyDigest(),deriveServerVerificationProfilePolicyDigest(),deriveExternalTrustReadinessPolicyDigest(),deriveStagingHsmP256BindingDigest()]);if(p.ceremonyPolicyDigest!==ceremonyPolicyDigest||p.providerPolicyDigest!==providerPolicyDigest||p.serverVerificationPolicyDigest!==serverVerificationPolicyDigest||p.externalTrustPolicyDigest!==externalTrustPolicyDigest||p.stagingHsmBindingDigest!==stagingHsmBindingDigest)return{valid:false,passport:null,error:'POLICY_DIGEST'};
  const{proof,...core}=p;if(proof!==`ETP-${upper16(await sha(canonical(core)))}`)return{valid:false,passport:null,error:'PROOF'};const parent=await readTrustAnchorReadinessPassport();if(!parent.valid||!parent.passport)return{valid:false,passport:null,error:'PARENT_MISSING'};if(parent.passport.proof!==p.parentTrustProof||parent.passport.parentRemoteProof!==p.parentRemoteProof||parent.passport.parentAuthorizationProof!==p.parentAuthorizationProof||parent.passport.parentReplayProof!==p.parentReplayProof||parent.passport.parentBackendProof!==p.parentBackendProof||parent.passport.boundaryLineage!==p.boundaryLineage||parent.passport.contractLineage!==p.contractLineage)return{valid:false,passport:null,error:'PARENT_CHAIN'};return{valid:true,passport:p,error:''};
}catch{return{valid:false,passport:null,error:'INVALID'};}}

export function buildExternalTrustPassportSnapshot(p:ExternalTrustReadinessPassport|null){if(!p)return'externalTrustPassport=NONE\nsecrets=NONE';return[`externalTrustPassport=v2/R13.8G`,`proof=${p.proof}`,`parentTrust=${p.parentTrustProof}`,`parentRemote=${p.parentRemoteProof}`,`parentAuthorization=${p.parentAuthorizationProof}`,`parentReplay=${p.parentReplayProof}`,`parentBackend=${p.parentBackendProof}`,`boundaryLineage=${p.boundaryLineage}`,`contractLineage=${p.contractLineage}`,`suite=${p.suitePassed}/${p.suiteTotal}`,`scope=${p.scope}`,`stagingHsmBinding=${p.stagingHsmBindingDigest}`,`stagingHsmEvidenceSha256=${p.stagingHsmEvidenceSha256}`,`ceremonyPolicyDigest=${p.ceremonyPolicyDigest}`,`providerPolicyDigest=${p.providerPolicyDigest}`,`serverVerificationPolicyDigest=${p.serverVerificationPolicyDigest}`,`externalTrustPolicyDigest=${p.externalTrustPolicyDigest}`,'stagingHsmP256=true','stagingHsmAttestation=true','manufacturerRootCurrentTimeValid=false','providerReviewStagingExceptionAccepted=true','productionProviderRootGate=OPEN','productionKms=false','productionKeyMaterial=false','serverVerifier=false','providerTrustRoots=false','serverReplayLedger=false','trustedServerClock=false','productionRelease=false','networkExecution=false','livePaymentExecution=false','settlement=false','secrets=NONE'].join('\n');}
